-- Rollback for Migration 0002
BEGIN;
DROP TRIGGER IF EXISTS trg_booking_status_history ON bookings;
DROP FUNCTION IF EXISTS public.track_booking_status_change();
DROP TABLE IF EXISTS device_tokens;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS booking_attempts;
DROP TABLE IF EXISTS staff_calendar;
DROP TABLE IF EXISTS booking_status_history;
DROP TABLE IF EXISTS booking_services;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS package_services;
DROP TABLE IF EXISTS packages;
DROP TABLE IF EXISTS service_required_skills;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS staff_time_off;
DROP TABLE IF EXISTS staff_breaks;
DROP TABLE IF EXISTS staff_working_hours;
DROP TABLE IF EXISTS staff_skills;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS skills;
DROP FUNCTION IF EXISTS public.set_updated_at();
COMMIT;
